---
- hosts: localhost
  #vars_files:
  #  - mylocalvarsfile.yml

  tasks:
  
    - name: Export all assets
      export:
        all: True
      register: export_output
  
    #- name: Include test var_from role
    #  include_role:
    #    name: test_vars_from
    #    #vars_from: var_bar.yml

    #- name: Include test var_from role with other vars file
    #  include_role:
    #    name: test_vars_from
    #    vars_from: var_foo.yml
...
